# Generated by Django 5.2.3 on 2025-07-08 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('branch_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ManpowerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Employee', 'Employee'), ('Contractor', 'Contractor')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('purchase_order', models.CharField(max_length=100, unique=True)),
                ('purchase_order_received', models.DateField()),
                ('total_days', models.PositiveIntegerField(blank=True, null=True)),
                ('classification', models.CharField(choices=[('GENSET A', 'GENSET A'), ('GENSET B', 'GENSET B'), ('GENSET C', 'GENSET C')], max_length=100)),
                ('description', models.TextField()),
                ('service_report_number', models.CharField(blank=True, null=True)),
                ('date_started', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField()),
                ('target_date_delayed', models.PositiveIntegerField(default=0)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('coc_number', models.CharField(blank=True, max_length=100, null=True)),
                ('dr_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Delayed', 'Delayed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20, null=True)),
                ('customer_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitoring.customerdetail')),
            ],
        ),
    ]
