# Generated by Django 5.2.3 on 2025-06-22 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order', models.CharField(max_length=100)),
                ('date_in_email', models.DateField()),
                ('total_days', models.PositiveIntegerField()),
                ('manpower_count', models.PositiveIntegerField()),
                ('time_total', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('remarks', models.CharField(choices=[('FOR BILLING', 'FOR BILLING'), ('FOR SIGNATURE', 'FOR SIGNATURE')], max_length=20)),
                ('date_started', models.DateField()),
                ('target_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Delayed', 'Delayed')], max_length=20)),
                ('customer_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.customerdetail')),
            ],
        ),
    ]
