# Generated by Django 5.2.3 on 2025-07-09 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_total', models.PositiveIntegerField(help_text='Total hours worked by all manpower this day')),
                ('manpower', models.ManyToManyField(to='monitoring.manpowerdetail')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_work_statuses', to='monitoring.purchaseorder')),
            ],
        ),
    ]
