# Generated by Django 5.2.3 on 2025-06-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManpowerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='manpower_count',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='manpower_total',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='manpower',
            field=models.ManyToManyField(blank=True, to='monitoring.manpowerdetail'),
        ),
    ]
