# Generated by Django 5.2.3 on 2025-07-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_dailyworkstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='manpower_total',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='work_hours_total',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='working_days_total',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
