# Generated by Django 5.2.3 on 2025-06-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_manpowerdetail_remove_purchaseorder_manpower_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='date_in_email',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='remarks',
            field=models.CharField(blank=True, choices=[('FOR BILLING', 'FOR BILLING'), ('FOR SIGNATURE', 'FOR SIGNATURE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(blank=True, choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Delayed', 'Delayed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='time_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
