# Generated by Django 5.2.3 on 2025-07-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_purchaseorder_manpower_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworkstatus',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyworkstatus',
            name='manpower',
            field=models.ManyToManyField(blank=True, null=True, to='monitoring.manpowerdetail'),
        ),
        migrations.AlterField(
            model_name='dailyworkstatus',
            name='time_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
