# Generated by Django 5.2.3 on 2025-07-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_dailyworkstatus_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworkstatus',
            name='manpower',
            field=models.ManyToManyField(blank=True, to='monitoring.manpowerdetail'),
        ),
    ]
