# Generated by Django 5.2.3 on 2025-06-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='remarks',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('FOR BILLING', 'FOR BILLING'), ('FOR SIGNATURE', 'FOR SIGNATURE')], max_length=20, null=True),
        ),
    ]
