# Generated by Django 5.2.3 on 2025-07-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_alter_dailyworkstatus_manpower'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworkstatus',
            name='itinenary_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
