# Generated by Django 5.2.3 on 2025-06-24 04:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_alter_purchaseorder_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='completion_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='date_recorded',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='item_model',
            field=models.CharField(blank=True, choices=[('GENSET A', 'GENSET A'), ('GENSET B', 'GENSET B'), ('GENSET C', 'GENSET C')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
