# Generated by Django 5.2.3 on 2025-06-24 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_purchaseorder_completion_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='date_recorded',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 6, 24, 4, 14, 41, 309107, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
