# Generated by Django 5.2.3 on 2025-07-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_dailyworkstatus_itinenary_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='manpower_type',
            field=models.CharField(blank=True, choices=[('employee', 'Employee Based'), ('contractor', 'Contractor Based'), ('both', 'Employee + Contractor Based')], max_length=20, null=True),
        ),
    ]
