# Generated by Django 5.2.3 on 2025-07-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_purchaseorder_manpower_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_target_date_adjusted',
            field=models.BooleanField(default=False),
        ),
    ]
