# Generated by Django 5.2.3 on 2025-07-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_purchaseorder_is_target_date_adjusted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='is_target_date_adjusted',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='target_date_status',
            field=models.CharField(choices=[('original', 'Original'), ('adjusted', 'Adjusted')], default='original', max_length=20),
        ),
    ]
