# Generated by Django 5.2.3 on 2025-06-24 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='date_in_email',
            field=models.DateField(default=datetime.datetime(2025, 6, 24, 8, 0, 44, 913178, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='description',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='item_model',
            field=models.CharField(choices=[('GENSET A', 'GENSET A'), ('GENSET B', 'GENSET B'), ('GENSET C', 'GENSET C')], default='GENSET A', max_length=20),
            preserve_default=False,
        ),
    ]
