# Generated by Django 5.2.3 on 2025-06-24 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_alter_purchaseorder_date_in_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='target_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 24, 8, 6, 7, 402538, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
