# Generated by Django 5.2.3 on 2025-07-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_remove_purchaseorder_is_target_date_adjusted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='service_report_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
