# Generated by Django 5.2.3 on 2025-06-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_alter_purchaseorder_target_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='service_report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
