# Generated by Django 5.2.3 on 2025-07-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_alter_purchaseorder_service_report_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_order',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
