# Generated by Django 5.2.3 on 2025-07-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_alter_purchaseorder_purchase_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
