# Generated by Django 5.2.3 on 2025-06-25 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_purchaseorder_service_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='remarks',
        ),
    ]
