# Generated by Django 5.2.3 on 2025-07-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_alter_purchaseorder_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='coc_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='dr_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='remarks',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='service_report_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
