# Generated by Django 5.2.3 on 2025-06-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_remove_purchaseorder_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='target_date_delayed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
