# Generated by Django 5.2.3 on 2025-07-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_alter_purchaseorder_coc_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='coc_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='dr_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_order',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='service_report_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
