# Generated by Django 5.2.3 on 2025-07-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_purchaseorder_target_date_delayed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='item_model',
            new_name='classification',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='completion_code',
            new_name='coc_number',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='delivery_code',
            new_name='dr_number',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='date_in_email',
            new_name='purchase_order_received',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='service_report',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='service_report_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
