# Generated by Django 5.2.3 on 2025-07-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0014_rename_item_model_purchaseorder_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Delayed', 'Delayed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20, null=True),
        ),
    ]
