# Generated by Django 5.2.3 on 2025-07-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0014_alter_purchaseorder_coc_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='branch_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='customer_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='manpowerdetail',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
