# Generated by Django 5.2.3 on 2025-07-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0015_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manpowerdetail',
            name='category',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Contractor', 'Contractor')], default='Employee', max_length=20),
            preserve_default=False,
        ),
    ]
