# Generated by Django 5.2.4 on 2025-07-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0016_alter_customerdetail_branch_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='customer_name',
            field=models.CharField(max_length=20),
        ),
    ]
