# Generated by Django 5.2.4 on 2025-07-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0017_alter_customerdetail_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworkstatus',
            name='itinenary_remarks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
