# Generated by Django 5.2.3 on 2025-07-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0017_purchaseorder_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='manpower_type',
            field=models.CharField(blank=True, choices=[('Employee Based', 'Employee Based'), ('Contractor Based', 'Contractor Based'), ('Employee & Contractor Based', 'Employee & Contractor Based')], editable=False, max_length=30, null=True),
        ),
    ]
