# Generated by Django 5.2.3 on 2025-07-08 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0018_purchaseorder_manpower_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='customer_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitoring.customerdetail'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_order',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
