# Generated by Django 5.2.4 on 2025-07-23 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0018_alter_dailyworkstatus_itinenary_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworkstatus',
            name='itinenary_remarks',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='dailyworkstatus',
            name='time_total',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
