# Generated by Django 5.2.3 on 2025-07-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0019_alter_purchaseorder_customer_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manpowerdetail',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
