# Generated by Django 5.2.3 on 2025-07-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0020_alter_manpowerdetail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manpowerdetail',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
