# Generated by Django 5.2.4 on 2025-07-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0021_alter_purchaseorder_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='classification',
            field=models.CharField(max_length=30),
        ),
    ]
