# Generated by Django 5.2.3 on 2025-07-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0022_alter_manpowerdetail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='branch_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='customer_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='classification',
            field=models.CharField(choices=[('GENSET A', 'GENSET A'), ('GENSET B', 'GENSET B'), ('GENSET C', 'GENSET C')], max_length=100),
        ),
    ]
