# Generated by Django 5.2.4 on 2025-07-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0022_alter_purchaseorder_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='branch_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='customer_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='manpower_type',
            field=models.CharField(blank=True, choices=[('employee', 'Employee Based'), ('contractor', 'Contractor Based'), ('helper', 'Helper Based'), ('employee_contractor', 'Employee + Contractor Based'), ('employee_helper', 'Employee + Helper Based'), ('contractor_helper', 'Contractor + Helper Based'), ('all', 'Employee + Contractor + Helper Based')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_order',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
