# Generated by Django 5.2.4 on 2025-08-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0024_alter_manpowerdetail_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerdetail',
            unique_together={('customer_name', 'branch_name')},
        ),
    ]
