# Generated by Django 5.2.4 on 2025-08-08 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0024_alter_manpowerdetail_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999.99)]),
            preserve_default=False,
        ),
    ]
