# Generated by Django 5.2.4 on 2025-07-29 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0025_alter_customerdetail_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerdetail',
            unique_together=set(),
        ),
    ]
