# Generated by Django 5.2.4 on 2025-08-07 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0025_purchaseorder_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999.99)]),
        ),
    ]
