# Generated by Django 5.2.4 on 2025-08-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0026_historicalpurchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='pic_status',
            field=models.CharField(blank=True, choices=[('w/pic', 'With Picture'), ('w/o pic', 'Without Picture')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='pms_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
