# Generated by Django 5.2.4 on 2025-10-07 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0027_purchaseorder_pic_status_purchaseorder_pms_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworkstatus',
            name='time_total',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
